//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donation()
        {
            this.AcceptorAccesses = new HashSet<AcceptorAccess>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> place { get; set; }
        public string address { get; set; }
        public Nullable<int> BloodType { get; set; }
        public bool gender { get; set; }
        public string phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastDon { get; set; }
        public Nullable<bool> isFree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcceptorAccess> AcceptorAccesses { get; set; }
        public virtual BloodType BloodType1 { get; set; }
        public virtual Place Place1 { get; set; }
    }
}
